### ISSUE TITLE
vue中css样式穿透

### ISSUE THREAD

**Issue by jikeyChang** [jikeyChang/points-issues#5]
> stylus的样式穿透 使用 >>>
```css
<style scoped>
  .wrapper>>>.swiper-pagination-bullet-active{
    margin-right:16px;
    margin-left:95px
  }
</style>
```

> sass和less的样式穿透 使用 /deep/
```css
<style lang="less"  scoped>
  .wrapper /deep/ .swiper-pagination-bullet-active{
      background: #fff;
    }
</style>
```
